apiVersion: v1
kind: Service
metadata:
  name: {{ include "moondream-server.fullname" . }}
  labels:
    {{- include "moondream-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "moondream-server.selectorLabels" . | nindent 4 }}
{{- if .Values.externalService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "moondream-server.fullname" . }}-external
  labels:
    {{- include "moondream-server.labels" . | nindent 4 }}
  {{- with .Values.externalService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.externalService.type }}
  ports:
    - port: {{ .Values.externalService.port }}
      targetPort: {{ .Values.externalService.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "moondream-server.selectorLabels" . | nindent 4 }}
{{- end }}
