apiVersion: v1
kind: ConfigMap
metadata:
  name: moondream-config
  namespace: moondream
  labels:
    app: moondream-station
data:
  # Configuration for Moondream Station
  host: "0.0.0.0"
  port: "8080"
  # Add other configuration options as needed
  log_level: "info"
  # Model cache settings
  model_cache_dir: "/data/.local/share/MoondreamStation/models"
  # Performance settings
  max_concurrent_requests: "10"
