apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moondream-data-pvc
  namespace: moondream
  labels:
    app: moondream-station
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd # Adjust based on your cluster's storage classes
